[tox]
skipsdist = true
envlist = py314

[testenv]
passenv = PYTHON_VERSION
allowlist_externals = uv
commands =
    uv sync --python {envpython}
    uv run python -m pytest tests --cov --cov-config=pyproject.toml --cov-report=xml
    uv run mypy
