services:
  db:
    image: postgres:19beta1-alpine
    environment:
      POSTGRES_USER: petstore
      POSTGRES_PASSWORD: petstore
      POSTGRES_DB: petstore
    ports:
      - "5432:5432"
    volumes:
      - petstore-db-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U petstore -d petstore"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    environment:
      DATABASE_URL: postgresql://petstore:petstore@db:5432/petstore
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  petstore-db-data:
